local _, addon = ...

-- Each NPC has a dedicated filesystem path. Core.lua can enable or disable
-- that path without comparing a secret UnitName value during Mythic+.
-- marker stores the default choice used by the in-game marker selector.
-- defaultEnabled=false keeps optional additions unchecked. addedIn triggers
-- that default once when an existing SavedVariables database is upgraded.
addon.NPC_DATABASE = {
    ["Kings Rest"] = {
        { name = "Half-Finished Mummy", path = "01", marker = "triangle" },
        { name = "Healing Tide Totem", path = "02", marker = "skull" },
        { name = "King A'akul", path = "03", marker = "skull" },
        { name = "King Rahu'ai", path = "04", marker = "skull" },
        { name = "Phantom Hex Priest", path = "05", marker = "moon" },
        { name = "Risen Hexer", path = "06", marker = "skull" },
        { name = "Seneschal M'bara", path = "07", marker = "diamond", defaultEnabled = false, addedIn = 2 },
        { name = "Shadow-Borne Champion", path = "08", marker = "skull" },
        { name = "Animated Guardian", path = "09", marker = "square", defaultEnabled = false, addedIn = 2 },
        { name = "Minion of Zul", path = "10", marker = "cross", defaultEnabled = false, addedIn = 2 },
        { name = "Umbral Warrior", path = "11", marker = "triangle", defaultEnabled = false, addedIn = 2 },
        { name = "Queen Wasi", path = "12", marker = "star", defaultEnabled = false, addedIn = 2 },
        { name = "King Timalji", path = "13", marker = "diamond", defaultEnabled = false, addedIn = 2 },
        { name = "Bloodsworn Assassin", path = "14", marker = "circle", defaultEnabled = false, addedIn = 2 },
        { name = "Guard Captain Atu", path = "15", marker = "square", defaultEnabled = false, addedIn = 2 },
        { name = "Queen Patiaa", path = "16", marker = "star", defaultEnabled = false, addedIn = 2 },
        { name = "Skeletal Hunting Raptor", path = "17", marker = "circle", defaultEnabled = false, addedIn = 2 },
        { name = "Purification Construct", path = "18", marker = "diamond", defaultEnabled = false, addedIn = 2 },
        { name = "Interment Construct", path = "19", marker = "square", defaultEnabled = false, addedIn = 2 },
        { name = "Embalming Fluid", path = "20", marker = "moon", defaultEnabled = false, addedIn = 2 },
        { name = "Spectral Shaman", path = "21", marker = "diamond", defaultEnabled = false, addedIn = 2 },
        { name = "Royal Berserker", path = "22", marker = "cross", defaultEnabled = false, addedIn = 2 },
        { name = "Honored Raptor", path = "23", marker = "triangle", defaultEnabled = false, addedIn = 2 },
        { name = "Ghostly Brute", path = "24", marker = "triangle", defaultEnabled = false, addedIn = 2 },
        { name = "Shadow of Zul", path = "25", marker = "diamond", defaultEnabled = false, addedIn = 2 },
    },
    ["Den of Nalorakk"] = {
        { name = "Earthwhisper Tender", path = "01", marker = "triangle" },
        { name = "Frigid Mauler", path = "02", marker = "cross" },
        { name = "Keen-Eyed Striker", path = "03", marker = "diamond" },
        { name = "Spirit of Hunger", path = "04", marker = "moon" },
        { name = "Starvation Effigy", path = "05", marker = "skull" },
        { name = "Stormbound Mystic", path = "06", marker = "square" },
        { name = "Territorial Matriarch", path = "07", marker = "skull" },
        { name = "Thronclaw Gatherer", path = "08", marker = "triangle", defaultEnabled = false, addedIn = 2 },
        { name = "Curious Yerling", path = "09", marker = "star", defaultEnabled = false, addedIn = 2 },
        { name = "Terra Rumbler", path = "10", marker = "cross", defaultEnabled = false, addedIn = 2 },
        { name = "Glacial Revenant", path = "11", marker = "moon", defaultEnabled = false, addedIn = 2 },
        { name = "Avatar of Determination", path = "12", marker = "diamond", defaultEnabled = false, addedIn = 2 },
        { name = "The Winter Squall", path = "13", marker = "square", defaultEnabled = false, addedIn = 2 },
        { name = "Ruthless Totemcaller", path = "14", marker = "diamond", defaultEnabled = false, addedIn = 2 },
        { name = "Bonded Beasttamer", path = "15", marker = "triangle", defaultEnabled = false, addedIn = 2 },
        { name = "Loyal Saberfang", path = "16", marker = "circle", defaultEnabled = false, addedIn = 2 },
        { name = "Grizzled Warbringer", path = "17", marker = "cross", defaultEnabled = false, addedIn = 2 },
        { name = "Loa Speaker Nanea", path = "18", marker = "moon", defaultEnabled = false, addedIn = 2 },
    },
    ["Murder Row"] = {
        { name = "Bribed Captain", path = "01", marker = "skull" },
        { name = "Bribed Guard", path = "02", marker = "skull" },
        { name = "Corrupted Warlock", path = "03", marker = "square" },
        { name = "Fel Invoker", path = "04", marker = "moon" },
        { name = "Felmaster Lucsei", path = "05", marker = "skull" },
        { name = "Felonious Mage", path = "06", marker = "diamond" },
        { name = "Seductive Sayaad", path = "07", marker = "star" },
        { name = "Shivan Punisher", path = "08", marker = "skull" },
        { name = "Wrathguard Flayer", path = "09", marker = "cross" },
        { name = "Row Hooligan", path = "10", marker = "cross", defaultEnabled = false, addedIn = 3 },
        { name = "Felwyrm", path = "11", marker = "circle", defaultEnabled = false, addedIn = 3 },
        { name = "Street Sneak", path = "12", marker = "triangle", defaultEnabled = false, addedIn = 3 },
        { name = "Massive Felwyrm", path = "13", marker = "square", defaultEnabled = false, addedIn = 3 },
        { name = "Nibbles", path = "14", marker = "star", defaultEnabled = false, addedIn = 3 },
        { name = "Kystia Manaheart", path = "15", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "Warehouse Worker", path = "16", marker = "triangle", defaultEnabled = false, addedIn = 3 },
        { name = "Keen Taskmaster", path = "17", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "Zaen Bladesorrow", path = "18", marker = "cross", defaultEnabled = false, addedIn = 3 },
        { name = "Trained Felhunter", path = "19", marker = "circle", defaultEnabled = false, addedIn = 3 },
        { name = "Unleashed Imp", path = "20", marker = "star", defaultEnabled = false, addedIn = 3 },
        { name = "Demon Fly", path = "21", marker = "triangle", defaultEnabled = false, addedIn = 3 },
        { name = "Xathuux the Annihilator", path = "22", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "Defiled Golem", path = "23", marker = "square", defaultEnabled = false, addedIn = 3 },
    },
    ["The Blinding Vale"] = {
        { name = "Leafy Grovecrawler", path = "01", marker = "square", defaultEnabled = false, addedIn = 3 },
        { name = "Lightfeather Petalwing", path = "02", marker = "star", defaultEnabled = false, addedIn = 3 },
        { name = "Radiant Spellsower", path = "03", marker = "diamond" },
        { name = "Sporeblight Belcher", path = "04", marker = "skull" },
        { name = "Virid Grovekeeper", path = "05", marker = "skull" },
        { name = "Lightgorged Lasher", path = "06", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "Lasher", path = "07", marker = "triangle", defaultEnabled = false, addedIn = 3 },
        { name = "Underbrush Stalker", path = "08", marker = "triangle", defaultEnabled = false, addedIn = 3 },
        { name = "Thorny Saptor", path = "09", marker = "cross", defaultEnabled = false, addedIn = 3 },
        { name = "Overgrown Hydra", path = "10", marker = "square", defaultEnabled = false, addedIn = 3 },
        { name = "Spineshield Beetle", path = "11", marker = "circle", defaultEnabled = false, addedIn = 3 },
        { name = "Luminous Thornmaw", path = "12", marker = "star", defaultEnabled = false, addedIn = 3 },
        { name = "Potatoad Matriarch", path = "13", marker = "diamond", defaultEnabled = false, addedIn = 3 },
    },
    ["Voidscar Arena"] = {
        { name = "Angry Krolusk", path = "01", marker = "circle", defaultEnabled = false, addedIn = 3 },
        { name = "Brutal Overseer", path = "02", marker = "triangle" },
        { name = "Chitigoth", path = "03", marker = "skull" },
        { name = "Devouring Brutalizer", path = "04", marker = "skull" },
        { name = "Dominated Brawler", path = "05", marker = "cross" },
        { name = "Enthralled Shaman", path = "06", marker = "diamond" },
        { name = "Kilivore Screamer", path = "07", marker = "star" },
        { name = "Protective Turtle", path = "08", marker = "square", defaultEnabled = false, addedIn = 3 },
        { name = "Voidminder", path = "09", marker = "moon" },
        { name = "Voidtouched Magi", path = "10", marker = "skull" },
        { name = "Longtooth Tuskarr", path = "11", marker = "circle", defaultEnabled = false, addedIn = 3 },
        { name = "Feral Saberon", path = "12", marker = "cross", defaultEnabled = false, addedIn = 3 },
        { name = "Lost Sethrak", path = "13", marker = "moon", defaultEnabled = false, addedIn = 3 },
        { name = "Raj'kess the Spellstorm", path = "14", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "Aegyra the Unyielding", path = "15", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "Sycophantic Tarasek", path = "16", marker = "triangle", defaultEnabled = false, addedIn = 3 },
        { name = "Raging Raptor", path = "17", marker = "cross", defaultEnabled = false, addedIn = 3 },
        { name = "Abducted Drakonid", path = "18", marker = "square", defaultEnabled = false, addedIn = 3 },
        { name = "Brutok", path = "19", marker = "star", defaultEnabled = false, addedIn = 3 },
        { name = "Savage Shredclaw", path = "20", marker = "cross", defaultEnabled = false, addedIn = 3 },
        { name = "Watchful Harrower", path = "21", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "Agitated Voidscythe", path = "22", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "Blistercreep", path = "23", marker = "circle", defaultEnabled = false, addedIn = 3 },
        { name = "Scavenging Siphoid", path = "24", marker = "triangle", defaultEnabled = false, addedIn = 3 },
        { name = "Toxic Creeper", path = "25", marker = "moon", defaultEnabled = false, addedIn = 3 },
    },
    ["Altar of Fangs"] = {
        { name = "High Evolutionist", path = "01", marker = "diamond" },
        { name = "Primal Serpent", path = "02", marker = "circle" },
        { name = "Rattling Writhe", path = "03", marker = "skull" },
        { name = "Ritual Chieftain", path = "04", marker = "skull" },
        { name = "Twinfang Harrower", path = "05", marker = "skull" },
        { name = "Ula'tek's Chosen", path = "06", marker = "skull" },
        { name = "Venom Leech", path = "07", marker = "circle", defaultEnabled = false, addedIn = 3 },
        { name = "Ravenous Descendant", path = "08", marker = "cross", defaultEnabled = false, addedIn = 3 },
        { name = "Rav'i", path = "09", marker = "star", defaultEnabled = false, addedIn = 3 },
        { name = "Bloodletter", path = "10", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "The Writhing Coil", path = "11", marker = "moon", defaultEnabled = false, addedIn = 3 },
        { name = "Blade of the Altar", path = "12", marker = "diamond", defaultEnabled = false, addedIn = 3 },
    },
    ["Ruby Life Pools"] = {
        { name = "Blazebound Destroyer", path = "01", marker = "skull" },
        { name = "Defier Draghar", path = "02", marker = "skull" },
        { name = "Flashfrost Chillweaver", path = "03", marker = "diamond" },
        { name = "High Channeler Ryvati", path = "04", marker = "skull" },
        { name = "Primal Juggernaut", path = "05", marker = "skull" },
        { name = "Primalist Cinderweaver", path = "06", marker = "square" },
        { name = "Tempest Channeler", path = "07", marker = "skull" },
        { name = "Earthbound Guardian", path = "08", marker = "square", defaultEnabled = false, addedIn = 3 },
        { name = "Deepstone Earthshaper", path = "09", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "Infused Whelp", path = "10", marker = "star", defaultEnabled = false, addedIn = 3 },
        { name = "Thunderhead", path = "11", marker = "circle", defaultEnabled = false, addedIn = 3 },
        { name = "Ruinous Stormbringer", path = "12", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "Ashseer Flamelasher", path = "13", marker = "moon", defaultEnabled = false, addedIn = 3 },
        { name = "Flamegullet", path = "14", marker = "cross", defaultEnabled = false, addedIn = 3 },
        { name = "Blazebound Firestorm", path = "15", marker = "square", defaultEnabled = false, addedIn = 3 },
        { name = "Storm Warrior", path = "16", marker = "triangle", defaultEnabled = false, addedIn = 3 },
        { name = "Primal Thundercloud", path = "17", marker = "diamond", defaultEnabled = false, addedIn = 3 },
    },
    ["Temple of Sethraliss"] = {
        { name = "Brood Tender", path = "01", marker = "moon" },
        { name = "Faithless Subjugator", path = "02", marker = "square" },
        { name = "Sand-Sworn Rider", path = "03", marker = "skull" },
        { name = "Sandfury Stonefist", path = "04", marker = "skull" },
        { name = "Storm Adept", path = "05", marker = "diamond" },
        { name = "Barbed Krolusk", path = "06", marker = "circle", defaultEnabled = false, addedIn = 3 },
        { name = "Sandswept Hunter", path = "07", marker = "triangle", defaultEnabled = false, addedIn = 3 },
        { name = "Shrouded Fang", path = "08", marker = "moon", defaultEnabled = false, addedIn = 3 },
        { name = "Lightning Serpent", path = "09", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "Poisonous Viper", path = "10", marker = "triangle", defaultEnabled = false, addedIn = 3 },
        { name = "Krolusk Matriarch", path = "11", marker = "square", defaultEnabled = false, addedIn = 3 },
        { name = "Dutiful Tamer", path = "12", marker = "star", defaultEnabled = false, addedIn = 3 },
        { name = "Agitated Nimbus", path = "13", marker = "circle", defaultEnabled = false, addedIn = 3 },
        { name = "Spark Channeler", path = "14", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "Imbued Stormcaller", path = "15", marker = "diamond", defaultEnabled = false, addedIn = 3 },
        { name = "Static Anomaly", path = "16", marker = "square", defaultEnabled = false, addedIn = 3 },
        { name = "Orb Watcher", path = "17", marker = "star", defaultEnabled = false, addedIn = 3 },
        { name = "Temple Disruptor", path = "18", marker = "cross", defaultEnabled = false, addedIn = 3 },
        { name = "Faithless Conscript", path = "19", marker = "triangle", defaultEnabled = false, addedIn = 3 },
        { name = "Twisted Hexxer", path = "20", marker = "moon", defaultEnabled = false, addedIn = 3 },
        { name = "Faithless Tormentor", path = "21", marker = "cross", defaultEnabled = false, addedIn = 3 },
        { name = "Corrupted Guardian", path = "22", marker = "square", defaultEnabled = false, addedIn = 3 },
        { name = "Essence Defiler", path = "23", marker = "diamond", defaultEnabled = false, addedIn = 3 },
    },
}
